dist: trusty
language: perl6
perl6: "2019.03"
before_install:
- curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
- PATH=$PATH:$HOME/.cargo/bin
script:
  make
